if("undefined"==typeof Mirando)var Mirando={};"undefined"==typeof Mirando.instanceRegistry&&function(){Mirando.instanceRegistry=new function(){var e={};this.getNextInstanceIdFor=function(b){e[b]?e[b]++:e[b]=1;return e[b]}}}();"undefined"==typeof Mirando.log&&function(){Mirando.log=new function(){var e=[];this.out=function(b){e.push(b)};this.dump=function(){if("undefined"==typeof console||"undefined"==typeof console.info)alert(e.join("\n"));else for(var b=0;b<e.length;b++)console.info(e[b]);e=[]}}}();
Mirando.ImpressionIdFactory=function(){function e(){var c,a;do c=window.parent,a++;while(c.parent!=c&&10>a);return c}var b=new Mirando.UuIdFactory;this.getOrCreate=function(){var c;a:{try{var a=e().mirImpId;if(a){c=b.parse(a);break a}}catch(d){}c=!1}if(!c){c=b.create();a:{a=c;try{e().mirImpId=a.toString()}catch(d){a=!1;break a}a=!0}if(!a)return null}return c}};
Mirando.UuIdFactory=function(){var e=new RegExp(/^[a-z0-9]{8}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{4}\-[a-z0-9]{12}$/),b=function(c){this.toString=function(){return c}};this.create=function(){for(var c=[],a=0;36>a;a++){var d="########-####-####-####-############".charAt(a);"#"==d?c.push("0123456789abcdef".charAt([Math.floor(16*Math.random())])):c.push(d)}return new b(c.join(""))};this.parse=function(c){if(null==e.exec(c))throw"Invalid UuId: "+c;return new b(c)}};
Mirando.QueryStringParser=function(){function e(){for(var a=document.getElementsByTagName("script"),d=null,c=/mirando.js/,b=a.length;0<b;b--)if(c.exec(a[b-1].src)){d=a[b-1];break}return d}var b=new RegExp(/(\?|#)(.*)/),c=function(){var c=[],d=b.exec(e().src);if(!d)return c;if(3==d.length)for(var d=d[2].split(/[;&]/),g=0;g<d.length;g++){var f=d[g].split("=");if(f&&2==f.length){var h=unescape(f[0]),f=unescape(f[1]);c[h]=f}}return c}();this.get=function(a){return c[a]};this.toString=function(){var a=
    [],d;for(d in c)"function"!=typeof c[d]&&"object"!=typeof c[d]&&a.push(d+"="+c[d]);return a.join("&")}};
Mirando.AdRequest=function(e,b,c,a){var d=this,g=("http:"==document.location.protocol?"http://":"https://")+"get.mirando.de/repository/%{adPlaceId}/%{impressionId}/%{instanceId}/?%{queryString}",f='[script type="text/javascript" src="%{url}"][/script]'.replace(/\[/g,"<").replace(/\]/g,">");this.render=function(){return f.replace("%{url}",d.getRequestUrl())};this.getRequestUrl=function(){return g.replace("%{adPlaceId}",e).replace("%{impressionId}",b).replace("%{queryString}",a).replace("%{instanceId}",
    c)}};
Mirando.showAd=function(){function e(){try{var c=document.cookie.match(/(?:^|;)\s?mid=(.*?)(?:;|$)/i);if(c){var d=unescape(c[1]);if(d)return d}if(window.localStorage&&window.localStorage.getItem)return localStorage.getItem("mid")}catch(a){}}function b(c,d){var a;(a=document.currentScript)||(a=document.getElementsByTagName("script"),a=a[a.length-1]);var b=Math.floor(1E5*Math.random()+1),e=document.createElement("div");e.setAttribute("id","testxy"+b);e.setAttribute("height","1px");e.setAttribute("width","1px");
    a.parentNode.appendChild(e);b=e;a="//get.mirando.de/download/mirando/publisher-quality/track.php?"+("vp="+Math.max(document.documentElement.clientWidth,window.innerWidth||0)+"x"+Math.max(document.documentElement.clientHeight,window.innerHeight||0));e=b.getBoundingClientRect();b.style.display="none";a+="&pos="+Math.round(e.left)+"x"+Math.round(e.top);var b=0,e=self.location.href,f=document.referrer;top.location.href!=self.location.href&&(b=1,f=top.location.href);a=a+("&impid="+c)+("&apid="+d)+("&iframe="+
        b);a+="&uri="+escape(e);f&&(a+="&refuri="+escape(f));a+="&client="+navigator.userAgent+";"+navigator.appName+";"+navigator.platform;a+="&pid="+mirPageViewID;for(var e=0,f=document.getElementsByTagName("script"),g=0;g<f.length;g++)b=f[g],b.src&&0<=b.src.indexOf("mirando.js#a="+d)&&0>b.src.indexOf("role=ss")&&e++;a+="&ac="+e;b=document.createElement("img");b.setAttribute("src",a);b.setAttribute("height","1px");b.setAttribute("width","1px");b.style.position="absolute";b.style.left="-1000px";b.style.top=
        "-1000px";document.body.appendChild(b);return a}var c=(new Mirando.QueryStringParser).get("a"),a=null;if(c){a=(new Mirando.ImpressionIdFactory).getOrCreate();if(!a){document.write("Auslieferung von Werbung im iFrame aus Sicherheitsgr\ufffdnden nicht m\ufffdglich.");return}try{if("undefined"!==typeof mirLimitDisplayWidthMin&&window.screen.availWidth&&window.screen.availWidth<mirLimitDisplayWidthMin)return}catch(h){console.log(h)}var d=(new Mirando.QueryStringParser).toString(),g=Mirando.instanceRegistry.getNextInstanceIdFor(c),
    f=e();f&&(d=(d?d+"&":"")+"mid="+f);top.location.href!=self.location.href&&(f=-1<top.location.href.indexOf("://")?top.location.href.split("/")[2]:top.location.href.split("/")[0],f=f.split(":")[0],d=(d?d+"&":"")+"topfqdn="+f);d=new Mirando.AdRequest(c,a.toString(),g,d);document.write(d.render())}else Mirando.log.out("unable to obtain adPlaceId from queryString");try{c&&a&&b(a.toString(),c)}catch(h){console.log(h)}};
if(!mirPageViewID)var mirPageViewID=Math.random().toString(36).slice(-12)+"-"+Math.random().toString(36).slice(-12)+"-"+Math.random().toString(36).slice(-12)+"-"+Math.random().toString(36).slice(-12);Mirando.showAd();for(var mirScripts=document.getElementsByTagName("script"),mirandoJsSrc=mirScripts[mirScripts.length-1].src,i=0;i<mirScripts.length;i++)"undefined"!==typeof mirScripts[i].src&&-1!=mirScripts[i].src.indexOf("mirando.js#a")&&(mirandoJsSrc=mirScripts[i].src);
var mirUriHash=-1!=mirandoJsSrc.indexOf("#")?mirandoJsSrc.split("#")[1].split("&")[0].split("=")[1]:-1!=mirandoJsSrc.indexOf("a=")?mirandoJsSrc.split("a=")[1].split("&")[0]:!1,mirUriHash=""+mirUriHash,blockBatchCounting=!1;
if(mirUriHash&&!blockBatchCounting)if("6950"==mirUriHash||"6951"==mirUriHash||"6952"==mirUriHash||"6944"==mirUriHash||"6945"==mirUriHash||"6947"==mirUriHash||"6948"==mirUriHash||"6946"==mirUriHash||"1830911"==mirUriHash)blockBatchCounting=!0;else if("11449579"==mirUriHash||"11449571"==mirUriHash)blockBatchCounting=!0;else if("11449573"==mirUriHash||"11449572"==mirUriHash||"11449570"==mirUriHash||"11449569"==mirUriHash||"11449577"==mirUriHash||"11449576"==mirUriHash||"11449575"==mirUriHash||"11449580"==
    mirUriHash)blockBatchCounting=!0;else if("13662560"==mirUriHash||"13662564"==mirUriHash||"13963930"==mirUriHash||"13964112"==mirUriHash||"13963917"==mirUriHash||"15586239"==mirUriHash||"15847019"==mirUriHash||"16045451"==mirUriHash||"16425060"==mirUriHash||"16425062"==mirUriHash||"16425065"==mirUriHash)blockBatchCounting=!0;if(!mirBatchInsert&&!blockBatchCounting){var mirBatchInsert=!0;document.write('<script type="text/javascript" src="http://c.t4ft.de/c/ftg_t.min.js?aid=1306&fcui=1774097&fcai=1774098&ffli=1774099&fpli=1774100">\x3c/script>')}
var motigoAdplaceIds=[11449569,11449570,11449571,11449572,11449573,11449574,11449575,11449576,11449577,11449578,11449579,11449580,12491744,12677054,12677055,12677056,12677057,12677058,12677059,12677060,12677061,12677062,12677063,12677064,12677065,12677066,13662558,13662559,13662560,13662561,13662562,13662563,13662564,13662565,13662566,13662567,13662568,13662569,13662570,13963930,13964112,13963917,15586239,15847019,16045451,16425060,16425062,16425065];
if(mirUriHash&&0>motigoAdplaceIds.indexOf(parseInt(mirUriHash))&&"undefined"===typeof captifyDone){var captifyDone=!0;(function(e,b,c,a,d,g,f){d=e.createElement(b);a=e.getElementsByTagName(b)[0];d.type="text/javascript";d.async=!0;d.src=c;a.parentNode.insertBefore(d,a)})(document,"script","https://p.cpx.to/p/11662/px.js")};